### ISSUE TITLE
Does this code work?

### ISSUE THREAD

**Issue by zhangrong1722** [hzycn/Spine-GAN#1]
Hi! Could this code work directly?

**Comment by zhyhan** [comment]
Sure, but the tf version is so old that should be updated.

**Comment by zhangrong1722** [comment]
Oh, that's great. And I wonder whether there is a PyTorch version.

**Comment by creating-py** [comment]
HI! May I ask if this code is the source code of Spine-gan: Semantic Segmentation of Multiple Spinal Structures? I am very interested in your article and want to take this opportunity to study it.

**Comment by zhyhan** [comment]
Yes, it is.

**Comment by creating-py** [comment]
Great！Thanks a lot.
